language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush
 - phpenv rehash
 - wget http://ftp.drupal.org/files/projects/drupal-7.14.tar.gz
 - tar -xf drupal-7.14.tar.gz
 - cd drupal-7.14
 - drush site-install standard --db-url=mysql://root:@localhost/drupal --yes
 - git clone --quiet --branch casper-test git://github.com/ericduran/views_load_more.git ./sites/all/modules/views_load_more
 - drush en views_load_more_test --yes
 - nohup drush run-server 8080 &
 - cd ..
 - git clone git://github.com/n1k0/casperjs.git
 - cd casperjs
 - git checkout tags/0.6.10
 - cd ./bin
 - "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

script:
 - "DISPLAY=:99.0 ./casperjs test ../../test/casperjs/"
